[build]
  base = "."
  publish = "dist/public"
  command = "npm --prefix client install && npm --prefix client run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
